iiwa:
  # Publish all joint states -----------------------------------
  state:
    type: joint_state_controller/JointStateController
    publish_rate: 200  # in Hz

  # Controllers ------------------------------------------------
  effort:
    type: effort_controllers/JointGroupEffortController
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

  position:
    type: position_controllers/JointGroupPositionController
    joints:
      - joint_0
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6