iiwa:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50 # Hz
    effort:
      joint_1:
        type: effort_controllers/JointEffortController
        joint: joint_1
      joint_2:
        type: effort_controllers/JointEffortController
        joint: joint_2
      joint_3:
        type: effort_controllers/JointEffortController
        joint: joint_3
      joint_4:
        type: effort_controllers/JointEffortController
        joint: joint_4
      joint_5:
        type: effort_controllers/JointEffortController
        joint: joint_5
      joint_6:
        type: effort_controllers/JointEffortController
        joint: joint_6
      joint_7:
        type: effort_controllers/JointEffortController
        joint: joint_7